kjo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views 

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
   
] 

posts/models.py
from django.db import models
# Create your models here.

class Post(models.Model):

    author = models.CharField(max_length=100)
    body = models.TextField()
    created_at =models.DateTimeField()

    def __str__(self):
        return f'{self.author}: {self.body}'

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.utils import timezone


# Create your views here.


def index(request):
    posts = Post.objects.all()

    context = {'posts': posts}

    return render(request, 'posts/index.html', context)


def detail(request, post_id):
    post = Post.objects.get(id=post_id)

    context = {'post': post}

    return render(request, 'posts/detail.html', context)


def new(request):
    return render(request, 'posts/new.html')


def create(request):
    author = request.POST['author']
    body = request.POST['body']
    post = Post(author=author, body=body, created_at=timezone.now())
    post.save()

    return redirect('posts:detail', post_id=post.id)

posts/templates/posts/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
    <title>Heestagram</title>
  </head>
  <body>
    <h1>Post Detail</h1>

    {% if post %}
      <h2>작성자</h2>
      <p>{{ post.author }}</p>

      <h2>본문</h2>
      <p>{{ post.body }}</p>

      <h2>게시일</h2>
      <p>{{ post.created_at }}</p>
    {% else %}
      <p>No Post.</p>
    {% endif %}

    <a href="{% url 'posts:index' %}">목록</a>
  </body>
</html>

posts/templates/posts/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
    <title>Heestagram</title>
  </head>
  <body>
    <h1>Post Detail</h1>

    {% if post %}
      <h2>작성자</h2>
      <p>{{ post.author }}</p>

      <h2>본문</h2>
      <p>{{ post.body }}</p>

      <h2>게시일</h2>
      <p>{{ post.created_at }}</p>
    {% else %}
      <p>No Post.</p>
    {% endif %}

    <a href="{% url 'posts:index' %}">목록</a>
  </body>
</html>

posts/templates/posts/index.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Posts</h1>

    {% if posts %}
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>작성자</th>
          <th>본문</th>
          <th>게시일</th>
          <th>상세</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <th>{{ post.id }}</th>
          <td>{{ post.author }}</td>
          <td>{{ post.body }}</td>
          <td>{{ post.created_at }}</td>
          <td><a href="{% url 'posts:detail' post.id %}">보기</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No Posts.</p>
    {% endif %}

    <a href="{% url 'posts:new' %}">글쓰기</a>
  </div>
{% endblock %}

posts/templates/posts/new.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
    <title>Heestagram</title>
  </head>
  <body>
    <h1>New Post</h1>

    <form action="{% url 'posts:create' %}" method="POST">
      {% csrf_token %}

      <h2>작성자</h2>
      <input type="text" name="author" />

      <h2>본문</h2>
      <textarea cols="40" rows="10" name="body"></textarea>

      <br />
      <input type="submit" value="작성하기">
    </form>

    <a href="{% url 'posts:index' %}">목록</a>
  </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css'%}" />
    <title>Heestagram</title>
    {% block style %}
    {% endblock %}
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>